# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.
import random


def cows_and_bulls(randomNumber, userGuess):
    cowbull = [0, 0]  # cows, then bulls
    for i in range(len(randomNumber)):
        if randomNumber[i] == userGuess[i]:
            cowbull[1] += 1
        else:
            cowbull[0] += 1
    return cowbull


if __name__ == "__main__":
    playing = True
    randomNumber = str(random.randint(1000, 9999))
    userCounts = 0

    print("Let's play a game of Cowbull!")  # explanation for the game
    print("I will generate a number, and you have to guess the numbers one digit at a time.")
    print("For every number in the wrong place, you get a cow. For every one in the right place, you get a bull.")
    print("The game ends when you get 4 bulls!")
    print("Type exit at any prompt to exit.")

    while playing:
        userGuess = input("Guess the number, it's between 1000 and 9999. Good Luck!")
        if userGuess == "exit":
            break
        cowbullcount = cows_and_bulls(randomNumber, userGuess)
        userCounts += 1

        print("You have " + str(cowbullcount[0]) + " cows, and " + str(cowbullcount[1]) + " bulls.")

        if cowbullcount[1] == 4:
            playing = False
            print("You win the game after " + str(userCounts) + " tries! The number was " + str(randomNumber))
            break
        else:
            print("Your guess isn't quite right.")
